import Head from 'next/head'
import Navbar from '../shared/Navbar'
import Footer from '../shared/Footer'

const MainLayout = ({ children }) => {
    return (
        <>
        <Head>
            <meta name ="desctiption" content="Generated by IT Geneous"></meta>
            <link ref="icon" href="/favicon.ico"/>
        </Head>
            <Navbar />
                { children }
            <Footer />
        </>
    )
}

export default MainLayout
